import { describe, expect, it } from "vitest";
import { destinations, properties, reviews, siteContent } from "@/content";
import { resolveBookingDestination } from "@/lib/booking/destination";
describe("version-controlled content", () => {
  it("keeps every active property normalized and source-auditable", () => { for (const property of properties.filter((record) => record.status === "active")) { expect(property.id).toBeTruthy(); expect(property.destinationId).toBeTruthy(); expect(property.sourceUrls.length).toBeGreaterThan(0); expect(resolveBookingDestination(property.booking).url).toMatch(/^https:/); expect(property.heroImage.alt).toBeTruthy(); expect(property.petPolicy).toBeTruthy(); expect(property.parking).toBeTruthy(); expect(property.accessibility).toBeTruthy(); expect(property.designerNote.designer).toBeTruthy(); expect(property.designerNote.paragraphs.length).toBeGreaterThan(0); } });
  it("keeps booking in fallback mode with no primary destination configured, and Airbnb as both the rollback and the independent review-attribution source", () => { for (const property of properties) { expect(property.booking.mode).toBe("fallback"); expect(property.booking.primary).toBeUndefined(); expect(property.booking.fallback.provider).toBe("airbnb"); expect(property.profiles?.airbnb?.url).toBe(property.booking.fallback.url); expect(property.profiles?.airbnb?.url).toBe(property.reviewSummary?.sourceUrl); } });
  it("publishes approved designer stories for the launch collection", () => { expect(properties.filter((property) => property.designerNote.status === "approved").map((property) => property.slug)).toEqual(["buttercup-beauty", "central-ave-socialization", "the-shamrock"]); });
  it("keeps the curated Buttercup gallery complete and accessible", () => { const buttercup = properties.find((property) => property.slug === "buttercup-beauty"); expect(buttercup?.gallery).toHaveLength(60); expect(buttercup?.gallery.every((image) => image.alt.length > 12)).toBe(true); expect(new Set(buttercup?.gallery.map((image) => image.src)).size).toBe(60); });
  it("publishes Buttercup's verified aggregate with five anonymous editorial highlights", () => { const summary = properties.find((property) => property.slug === "buttercup-beauty")?.reviewSummary; expect(summary).toMatchObject({ rating: 4.96, count: 75, sourceLabel: "Airbnb" }); expect(summary?.highlights).toHaveLength(5); expect(summary?.editorialNote).toMatch(/anonymous.*paraphrased/i); });
  it("keeps Central Ave's photography and anonymous review summary complete", () => { const central = properties.find((property) => property.slug === "central-ave-socialization"); expect(central?.gallery).toHaveLength(42); expect(central?.gallery.every((image) => image.alt.length > 12)).toBe(true); expect(new Set(central?.gallery.map((image) => image.src)).size).toBe(42); expect(central?.reviewSummary).toMatchObject({ rating: 5, count: 8, sourceLabel: "Airbnb" }); expect(central?.reviewSummary?.highlights).toHaveLength(5); });
  it("keeps The Shamrock's photography and anonymous review summary complete", () => { const shamrock = properties.find((property) => property.slug === "the-shamrock"); expect(shamrock?.gallery).toHaveLength(33); expect(shamrock?.gallery.every((image) => image.alt.length > 12)).toBe(true); expect(new Set(shamrock?.gallery.map((image) => image.src)).size).toBe(33); expect(shamrock?.reviewSummary).toMatchObject({ rating: 5, count: 6, sourceLabel: "Airbnb" }); expect(shamrock?.reviewSummary?.highlights).toHaveLength(5); });
  it("keeps relationships valid and unapproved reviews unpublished", () => { expect(properties.every((property) => destinations.some((destination) => destination.id === property.destinationId))).toBe(true); expect(reviews.filter((review) => review.permissionStatus !== "approved")).toHaveLength(0); });
  it("uses Ray's temporary public contact destination consistently", () => { expect(siteContent.contactEmail).toBe("ray@utopiahomes.com"); expect(siteContent.ownerEmail).toBe("ray@utopiahomes.com"); });
});
