import type { Property } from "@/types/content";
import { propertySchema, validateCollection } from "./schemas";

const buttercupGallery = ([
  ["arrival", "Front exterior and welcoming entrance of Buttercup Beauty"],
  ["outdoors", "Heated private pool across the fenced Buttercup backyard"],
  ["gathering", "Open living room connecting the kitchen and dining spaces"],
  ["arrival", "Street view of the Wildwood Crest shore home"],
  ["outdoors", "Covered pool and backyard prepared for a day outside"],
  ["outdoors", "Private hot tub beneath the covered backyard patio"],
  ["outdoors", "Poolside lounge chairs for a large group"],
  ["outdoors", "Backyard patio with grill and relaxed seating"],
  ["outdoors", "Reclining chairs arranged beside the pool"],
  ["outdoors", "Steps from the pool patio into the house"],
  ["outdoors", "Covered outdoor dining beside the private hot tub"],
  ["outdoors", "Outdoor sectional under the covered patio"],
  ["outdoors", "Covered backyard dining table for group meals"],
  ["bathrooms", "Subway-tile shower with matte black fixtures"],
  ["bathrooms", "Full bathroom shower with graphic grid curtain"],
  ["bathrooms", "Bright full bathroom with tiled shower and natural light"],
  ["bathrooms", "Full bathroom with shower and softly filtered window light"],
  ["kitchen-dining", "Expansive white kitchen island with seating for five"],
  ["kitchen-dining", "Kitchen island and counter seating viewed from the dining room"],
  ["kitchen-dining", "Modern kitchen with generous preparation space"],
  ["kitchen-dining", "Open kitchen, dining, and living spaces for a full house"],
  ["kitchen-dining", "Long dining table beside the open kitchen"],
  ["kitchen-dining", "Dining room connected directly to the kitchen"],
  ["kitchen-dining", "Dining table and statement lighting in the open-plan interior"],
  ["kitchen-dining", "Dining area arranged for shared group meals"],
  ["kitchen-dining", "Kitchen and dining spaces viewed from the central hallway"],
  ["bathrooms", "Bright bathroom with simple botanical artwork"],
  ["bathrooms", "Convenient first-floor powder room"],
  ["gathering", "Main living room with layered seating and a colorful rug"],
  ["gathering", "Media wall and fireplace in the main living room"],
  ["gathering", "Oversized sectional arranged around the living room coffee table"],
  ["gathering", "Main living room viewed from behind the sectional"],
  ["gathering", "Comfortable sectional and central gathering space"],
  ["gathering", "Pair of reading chairs beside the living room windows"],
  ["gathering", "Large living room with multiple conversation areas"],
  ["gathering", "Sofa table seating behind the main sectional"],
  ["gathering", "Sliding barn door and flexible seating beside the living room"],
  ["gathering", "Main living room arranged for a large family"],
  ["gathering", "Open-plan living space stretching toward the kitchen"],
  ["entertainment", "Game room with foosball and sectional seating"],
  ["entertainment", "Foosball table at the center of the game room"],
  ["entertainment", "Wide game room with lounge and high-top seating"],
  ["entertainment", "Game room arranged for playing and relaxing together"],
  ["entertainment", "Sectional seating in the dedicated game room"],
  ["entertainment", "Television and foosball area in the game room"],
  ["entertainment", "Game room media wall and foosball table"],
  ["gathering", "Bright enclosed porch with flexible seating"],
  ["bedrooms", "Guest bedroom with a daybed beneath sunlit windows"],
  ["bedrooms", "Guest bedroom with metal bed frame and corner windows"],
  ["bedrooms", "Calm guest bedroom with a blush bed and blackout curtains"],
  ["bedrooms", "Guest bedroom with a dark wood bed and blue bedding"],
  ["bedrooms", "Bedroom with two coordinating beds for family groups"],
  ["bedrooms", "Bedroom with two full beds and balcony doors"],
  ["bedrooms", "Sunlit guest bedroom with daybed and layered linens"],
  ["bedrooms", "Flexible bedroom with a futon and additional sleeping space"],
  ["bedrooms", "Playful guest bedroom with blush bedding and cat artwork"],
  ["bedrooms", "Twin-bed guest room designed for shared stays"],
  ["bedrooms", "Upstairs bedroom with two beds beneath the eaves"],
  ["bedrooms", "Upstairs twin bedroom with coordinated bedding"],
  ["bedrooms", "Sunlit upstairs bedroom with two iron-frame beds"],
] as const).map(([category, alt], index) => ({ src: `/images/buttercup/${String(index + 1).padStart(2, "0")}.webp`, alt, category }));

const centralAveGallery = ([
  [5, "arrival", "Front exterior and covered porch of Central Ave Socialization"],
  [1, "outdoors", "Private pool and sun loungers in the fenced backyard"],
  [29, "gathering", "Oversized sectional anchoring the main living room"],
  [16, "kitchen-dining", "Open dining space connecting the kitchen and living room"],
  [8, "bedrooms", "Bright bedroom with two blue beds and room to settle in"],
  [12, "details", "Welcoming entry and natural wood floors"],
  [13, "gathering", "Media wall in the relaxed main living space"],
  [14, "gathering", "Second lounge with soft seating and shore-house character"],
  [15, "details", "Coffee station and thoughtful everyday conveniences"],
  [28, "gathering", "Quiet sitting corner beside a sunlit window"],
  [30, "gathering", "Main sectional arranged for conversation and movie nights"],
  [31, "details", "Entry console with a playful North Wildwood welcome"],
  [32, "gathering", "Open living room viewed from the dining area"],
  [33, "gathering", "Wide living space with several places to gather"],
  [34, "gathering", "Television wall and coastal details in the main room"],
  [35, "gathering", "Comfortable central lounge for a full house"],
  [37, "details", "Interior stair and landing connecting the home’s levels"],
  [41, "details", "Front entry with hooks and a landing place for beach gear"],
  [42, "details", "Hallway console and woven wall detail"],
  [6, "bedrooms", "Bedroom with twin bed, television, and blackout curtains"],
  [7, "bedrooms", "Sunlit bedroom with a daybed and layered pillows"],
  [9, "bedrooms", "Calm bedroom with a generous upholstered bed"],
  [10, "bedrooms", "Guest bedroom with soft neutral bedding"],
  [11, "bedrooms", "Bedroom media console and full-length mirror"],
  [38, "bedrooms", "Blue guest room tucked beyond the upstairs hall"],
  [39, "bedrooms", "Second view into the flexible blue bedroom"],
  [17, "bathrooms", "Dark green bathroom with matte-black fixtures"],
  [18, "bathrooms", "Bright tiled shower with built-in corner shelf"],
  [19, "bathrooms", "Full shower prepared with guest essentials"],
  [20, "bathrooms", "Compact green bathroom with a modern vanity"],
  [2, "outdoors", "Pool deck with outdoor lounge and entertaining space"],
  [3, "outdoors", "Private backyard pool framed by lounge chairs"],
  [4, "outdoors", "Poolside bar seating beneath the converted bonus room"],
  [21, "outdoors", "Private hot tub beside the house"],
  [22, "outdoors", "Covered front porch with seating for a quiet morning"],
  [23, "outdoors", "Upper deck overlooking the private pool"],
  [24, "arrival", "Side entrance with a simple Wildwood welcome"],
  [25, "details", "Playful shore-house details in the outdoor entertaining space"],
  [26, "arrival", "Central Ave exterior from the neighborhood sidewalk"],
  [27, "outdoors", "Hot tub positioned for private evenings outdoors"],
  [36, "outdoors", "Close view of the hot tub beneath the open sky"],
  [40, "details", "Interior staircase leading to the separate upper level"],
] as const).map(([number, category, alt]) => ({ src: `/images/central-ave/${String(number).padStart(2, "0")}.webp`, alt, category }));

const records = [
  {
    id: "airbnb-639163446287777223", name: "Buttercup Beauty", slug: "buttercup-beauty", status: "active", featured: true,
    destinationId: "destination-wildwood", city: "Wildwood Crest", state: "New Jersey", propertyType: "Entire home",
    shortDescription: "A spacious Wildwood Crest gathering place with a heated pool, hot tub, and room for the whole family.",
    fullDescription: "Buttercup Beauty is a generous shore home designed around time together. Its open living spaces, game room, and fenced backyard make it especially well suited to multigenerational groups and friends traveling with dogs.",
    heroImage: buttercupGallery[0],
    gallery: buttercupGallery,
    maxGuests: 22, bedrooms: 7, beds: 13, bathrooms: 3.5,
    amenities: [
      { name: "Outside", amenities: ["Shared beach access", "Heated private pool", "Private hot tub", "Large fenced backyard"] },
      { name: "At home", amenities: ["Kitchen", "Wi-Fi", "In-unit washer and dryer", "Smart TVs", "Foosball table"] },
    ],
    uniqueFeatures: ["Approximately 3,200 square feet of interior space", "Heated private pool and eight-person hot tub", "Game room, covered dining area, and bakery directly across the street"],
    designerNote: { designer: "Meghan", role: "Interior design", headline: "Three generations. One Wildwood experience.", paragraphs: ["Buttercup Beauty was designed around multigenerational hosting—a place where grandparents, parents, and children can come together in Wildwood and share one experience without giving up the comfort each generation needs.", "Livability guided the redesign. A large central living area gives the whole family room to gather, while multiple seating moments and thoughtful design elements create places to connect throughout the home. Every decision was made to help a large family settle in naturally, spend meaningful time together, and leave with a shared collection of Wildwood memories."], status: "approved" },
    reviewSummary: {
      rating: 4.96,
      count: 75,
      sourceLabel: "Airbnb",
      sourceUrl: "https://www.airbnb.com/rooms/639163446287777223",
      lastVerifiedAt: "2026-08-23",
      editorialNote: "Anonymous guest feedback, condensed and paraphrased from verified five-star Airbnb reviews.",
      highlights: [
        "A natural setup for several families, with plenty of room to gather and still spread out.",
        "The heated pool and hot tub made a large-family weekend feel especially memorable.",
        "Clean, comfortable, and thoughtfully equipped for a full house—not a stripped-down rental.",
        "An easy walk to the beach, boardwalk, neighborhood food, and the bakery across the street.",
        "Thoughtful extras and responsive hosting left guests already planning another stay.",
      ],
    },
    petPolicy: "Dogs of any size are allowed, according to the source listing.",
    parking: "Parking for 4 cars.",
    accessibility: "The source description states that guests climb a few stairs at the entrance; no formal accessibility features are listed.",
    bookingUrl: "https://www.airbnb.com/rooms/639163446287777223", sourceUrls: ["https://www.airbnb.com/rooms/639163446287777223"],
    sourceSnapshot: { listingTitle: "7 Bedroom Pet Friendly Gorgeous Home Pool+Hot Tub", locationLabel: "Entire home in Wildwood Crest, New Jersey", displayedCapacity: "16+ guests", statedSleeps: 22, disclosedAmenityCount: 60, factualSummary: "Seven-bedroom, 3.5-bath entire home on Buttercup Road with a fenced backyard, seasonal heated in-ground pool, private hot tub, and shared beach access." },
    sourceAudit: { lastCheckedAt: "2026-08-23", factStatus: "partial", photographyRights: "approved", reviewRights: "pending", notes: ["Official Utopia name, 22-guest capacity, four-car parking, and heated-private-pool facts approved by Ray on 2026-08-23.", "Airbnb's summary shows 16+ guests while the approved Utopia capacity is 22.", "Airbnb shows 13 beds, while its sleeping-area breakdown also lists couches and a sofa bed.", "Ray owns the photography and approves its use on Utopia Homes; verbatim review publication rights remain pending. Public review highlights are anonymous editorial paraphrases."] },
    seoTitle: "Buttercup Beauty, Wildwood Crest | Utopia Homes", seoDescription: "Explore Buttercup Beauty, a seven-bedroom Wildwood Crest group home with a heated private pool, hot tub, and fenced backyard.",
  },
  {
    id: "airbnb-1137760792304016998", name: "Central Ave Socialization", slug: "central-ave-socialization", status: "active", featured: true,
    destinationId: "destination-wildwood", city: "North Wildwood", state: "New Jersey", propertyType: "Entire home",
    shortDescription: "A relaxed North Wildwood shore house with a heated private pool, hot tub, and easy beach access.",
    fullDescription: "Central Ave Socialization is a recently renovated group retreat built around easy time together. An open living area and fully fenced backyard create a welcoming home base for beach days, pool time, and evenings with the whole crew—including dogs.",
    heroImage: centralAveGallery[0],
    gallery: centralAveGallery,
    maxGuests: 22, bedrooms: 7, beds: 18, bathrooms: 3.5,
    amenities: [
      { name: "Outside", amenities: ["Beach access", "Heated private pool", "Hot tub", "Fully fenced backyard", "Patio seating and fire pit"] },
      { name: "At home", amenities: ["Kitchen", "Wi-Fi", "TV", "Washer", "In-unit dryer"] },
    ],
    uniqueFeatures: ["Approximately a five-minute walk to Albert I. Allen Memorial Park", "Heated private pool and hot tub in a fully fenced backyard", "Seven bedrooms and eighteen listed beds for large-group stays"],
    designerNote: { designer: "Meghan", role: "Interior design", headline: "Made for gathering. Designed to feel lived in.", paragraphs: ["Central Ave Socialization was designed around hosting events and giving large groups multiple living areas where they can come together. The goal was a home that felt genuinely lived in—not another sterile vacation rental.", "That meant choosing extremely comfortable oversized couches, adding blackout shades in every bedroom, and selecting artwork that entertains as much as it decorates. Every space is intended to help a full house settle in, connect, and feel at home together."], status: "approved" },
    reviewSummary: {
      rating: 5,
      count: 8,
      sourceLabel: "Airbnb",
      sourceUrl: "https://www.airbnb.com/rooms/1137760792304016998",
      lastVerifiedAt: "2026-08-23",
      editorialNote: "Anonymous guest feedback, condensed and paraphrased from verified five-star Airbnb reviews.",
      highlights: [
        "A great location for a Wildwood group, close enough to walk to the beach and boardwalk.",
        "The poolside bonus room and separate upper level gave everyone more ways to spend time together.",
        "Families loved the outdoor space, from the pool and patio seating to room for the dogs to play.",
        "Comfortable furniture, useful supplies, and thoughtful details made the house feel genuinely lived in.",
        "Responsive hosting and an easy group setup left guests eager to recommend the home and return.",
      ],
    },
    petPolicy: "Dogs of all sizes are welcome, according to the source listing.",
    parking: "Parking for 3 cars.",
    accessibility: "No accessibility features or limitations are stated in the source listing.",
    bookingUrl: "https://www.airbnb.com/rooms/1137760792304016998", sourceUrls: ["https://www.airbnb.com/rooms/1137760792304016998"],
    sourceSnapshot: { listingTitle: "Private Pool & Hot Tub- sleeps 22 & pups welcome!", locationLabel: "Entire home in North Wildwood, New Jersey", displayedCapacity: "16+ guests", statedSleeps: 22, disclosedAmenityCount: 63, factualSummary: "Recently renovated seven-bedroom entire home with a large open living area, private pool, hot tub, fenced backyard, beach access, and private access to the property." },
    sourceAudit: { lastCheckedAt: "2026-08-23", factStatus: "partial", photographyRights: "approved", reviewRights: "pending", notes: ["Official Utopia name, 22-guest capacity, three-car parking, and heated-private-pool facts approved by Ray on 2026-08-23.", "Airbnb's summary lists 3.5 baths while the description says four bathrooms; Utopia displays the approved current value of 3.5.", "The description calls the pool in-ground while a listing highlight calls it above-ground.", "Airbnb's summary shows 16+ guests while the approved Utopia capacity is 22.", "Ray owns the photography and approves its use on Utopia Homes; verbatim review publication rights remain pending. Public review highlights are anonymous editorial paraphrases."] },
    seoTitle: "Central Ave Socialization | Utopia Homes", seoDescription: "Explore Central Ave Socialization, a seven-bedroom North Wildwood group home with a heated private pool, hot tub, and beach access.",
  },
  {
    id: "airbnb-1629070581710289311", name: "The Shamrock", slug: "the-shamrock", status: "active", featured: true,
    destinationId: "destination-wildwood", city: "Wildwood", state: "New Jersey", propertyType: "Entire home",
    shortDescription: "A colorful Wildwood original, made for milestone weekends and the whole crew.",
    fullDescription: "Big groups deserve a home with just as much personality. The Shamrock brings everyone together in a restored piece of Wildwood history, with generous shared spaces and a location close to the beach, boardwalk, and downtown.",
    heroImage: { src: "/images/shamrock/exterior-main.avif", alt: "The colorful exterior of The Shamrock in Wildwood" },
    gallery: [
      { src: "/images/shamrock/exterior-main.avif", alt: "The colorful exterior and street corner of The Shamrock" },
      { src: "/images/shamrock/exterior-green.avif", alt: "Green facade and upper decks of The Shamrock" },
      { src: "/images/shamrock/interior-open.avif", alt: "Large open interior gathering space" },
      { src: "/images/shamrock/exterior-detail.avif", alt: "Street-level exterior detail of The Shamrock" },
      { src: "/images/shamrock/bathroom.avif", alt: "Bright blue and white bathroom interior" },
    ],
    maxGuests: 32, bedrooms: 10, beds: 19, bathrooms: 5,
    amenities: [
      { name: "Location", amenities: ["Shared beach access", "About two blocks from the boardwalk", "Walkable to downtown Wildwood"] },
      { name: "At home", amenities: ["Kitchen", "Wi-Fi", "Dedicated workspace", "HDTV", "Washer and in-unit dryer", "Central air conditioning"] },
    ],
    uniqueFeatures: ["A restored piece of the historic Shamrock property", "Ten bedrooms, four living rooms, and two decks", "Garage and driveway parking for six cars"],
    designerNote: { designer: "Meghan", role: "Interior design", headline: "A Wildwood original, carried forward.", paragraphs: ["The Shamrock is part of Wildwood history. The Shamrock Bar & Grill is the oldest bar and grill in Wildwood, and the house itself was moved from a block away rather than torn down—preserving a piece of that history for what came next.", "We wanted the home to retain as much of its historic charm as possible while still introducing a point of view of our own. The result is an intentional mix of old and new. Rooms such as Marilyn Monroe and Motorcycle preserve much of the historic house’s look and spirit, while Puppy Love and Mermaid were transformed more dramatically.", "Across every room, the goal remained the same: create a distinct experience with a personality guests would remember, just like The Shamrock itself."], status: "approved" },
    petPolicy: "Dogs of all shapes and sizes are allowed, according to the source listing.",
    parking: "Parking for 6 cars.",
    accessibility: "No accessibility features or limitations are stated in the source listing.",
    bookingUrl: "https://www.airbnb.com/rooms/1629070581710289311", sourceUrls: ["https://www.airbnb.com/rooms/1629070581710289311"],
    sourceSnapshot: { listingTitle: "Shamrock Shindigs for 30+ people!", locationLabel: "Entire home in Wildwood, New Jersey", displayedCapacity: "16+ guests", statedSleeps: 30, disclosedAmenityCount: 64, factualSummary: "Restored ten-bedroom Wildwood home with four living rooms, five baths, two decks, a large garage, shared beach access, and a location close to the beach and boardwalk." },
    sourceAudit: { lastCheckedAt: "2026-08-23", factStatus: "partial", photographyRights: "approved", reviewRights: "pending", notes: ["Official Utopia name, 32-guest capacity, six-car parking, and no-pool facts approved by Ray on 2026-08-23.", "Airbnb displays 16+ guests; the source title says 30+ while Utopia's approved advertised capacity is 32.", "The summary states ten bedrooms and nineteen beds, but the visible sleeping-area list shows only nine named bedrooms plus a living room.", "Source parking counts vary; Utopia displays Ray's approved six-car capacity.", "Ray owns the photography and approves its use on Utopia Homes; review publication rights remain pending."] },
    seoTitle: "The Shamrock, Wildwood | Utopia Homes", seoDescription: "Explore The Shamrock, a restored ten-bedroom Wildwood landmark for up to 32 guests near the beach and boardwalk.",
  },
];

export const properties: Property[] = validateCollection(propertySchema, records, "properties");
