import { z } from "zod";

export const imageSchema = z.object({ src: z.string().min(1), alt: z.string().min(1) });
const designerNoteSchema = z.object({ designer: z.string().min(1), role: z.string().min(1), headline: z.string().min(1), paragraphs: z.array(z.string().min(1)).min(1), status: z.enum(["approved", "pending"]) });
export const propertySchema = z.object({
  id: z.string().min(1), name: z.string().min(1), slug: z.string().regex(/^[a-z0-9-]+$/), status: z.enum(["draft", "active", "hidden", "archived"]), featured: z.boolean(), destinationId: z.string().min(1), city: z.string().min(1), state: z.string(), propertyType: z.string().min(1), shortDescription: z.string().min(1), fullDescription: z.string().min(1), heroImage: imageSchema, gallery: z.array(imageSchema).min(1), maxGuests: z.number().int().positive().optional(), bedrooms: z.number().nonnegative().optional(), beds: z.number().nonnegative().optional(), bathrooms: z.number().nonnegative().optional(), amenities: z.array(z.object({ name: z.string().min(1), amenities: z.array(z.string().min(1)) })), uniqueFeatures: z.array(z.string().min(1)), designerNote: designerNoteSchema, petPolicy: z.string(), parking: z.string(), accessibility: z.string(), bookingUrl: z.string().url(), sourceUrls: z.array(z.string().url()).min(1), sourceSnapshot: z.object({ listingTitle: z.string().min(1), locationLabel: z.string().min(1), displayedCapacity: z.string().min(1), statedSleeps: z.number().int().positive().optional(), disclosedAmenityCount: z.number().int().positive().optional(), factualSummary: z.string().min(1) }), sourceAudit: z.object({ lastCheckedAt: z.string().optional(), factStatus: z.enum(["verified", "partial", "pending"]), photographyRights: z.enum(["approved", "pending", "denied"]), reviewRights: z.enum(["approved", "pending", "denied"]), notes: z.array(z.string()) }), seoTitle: z.string().min(1), seoDescription: z.string().min(1),
});
export const destinationSchema = z.object({ id: z.string().min(1), name: z.string().min(1), slug: z.string().regex(/^[a-z0-9-]+$/), city: z.string().min(1), state: z.string(), shortDescription: z.string().min(1), longDescription: z.string().min(1), heroImage: imageSchema, featured: z.boolean(), seoTitle: z.string().min(1), seoDescription: z.string().min(1) });
export const reviewSchema = z.object({ id: z.string().min(1), propertyId: z.string().optional(), author: z.string().min(1), quote: z.string().min(1), rating: z.number().min(1).max(5).optional(), source: z.string().min(1), permissionStatus: z.enum(["approved", "pending", "denied"]) });
export const faqSchema = z.object({ id: z.string().min(1), category: z.enum(["stays", "owners", "membership", "design", "general"]), question: z.string().min(1), answer: z.string().min(1), sortOrder: z.number().int() });
export const campaignSchema = z.object({ id: z.string().min(1), slug: z.string().regex(/^[a-z0-9-]+$/), name: z.string().min(1), partner: z.string().min(1), eyebrow: z.string().min(1), headline: z.string().min(1), description: z.string().min(1), heroImage: imageSchema, ctaLabel: z.string().min(1), ctaUrl: z.string().min(1), rulesUrl: z.string().url().optional(), active: z.boolean(), seoTitle: z.string().min(1), seoDescription: z.string().min(1) });
export function validateCollection<T>(schema: z.ZodType<T>, records: unknown[], label: string): T[] { const result = z.array(schema).safeParse(records); if (!result.success) throw new Error(`Invalid ${label} content: ${result.error.message}`); return result.data; }
