import { CTASection } from "@/components/CTASection";
import { Hero } from "@/components/Hero";
import { PropertyCard } from "@/components/PropertyCard";
import { cms } from "@/lib/cms";
import Image from "next/image";
import Link from "next/link";
import { LeadForm } from "@/components/forms/LeadForm";

export default async function Home() {
  const [properties, destinations] = await Promise.all([cms.getProperties(), cms.getDestinations()]);
  const featured = properties[0];
  return <><Hero image={featured.heroImage} /><section className="section intro"><p className="eyebrow">The Utopia standard</p><h2>Remarkable homes.<br /><em>Effortless stays.</em></h2><div className="intro-copy"><p>We believe the best getaways begin with a home that has a point of view—and hospitality that makes everything else feel easy.</p><a className="text-link" href="#collection">Discover Utopia <span aria-hidden="true">→</span></a></div></section><section className="section featured" id="collection"><div className="section-heading"><div><p className="eyebrow">The collection</p><h2>Meet the places<br />you’ll talk about later.</h2></div><p>Homes with character, space to gather, and the details that turn a weekend away into a story worth keeping.</p></div><div className="property-grid">{properties.map((property, index) => <PropertyCard key={property.id} property={property} index={index + 1} />)}</div></section><section className="editorial"><div className="editorial-number">U / 01</div><div><p className="eyebrow eyebrow-light">Stay distinctly</p><h2>Not just a place<br />to sleep. A reason<br /><em>to go.</em></h2></div><p>From colorful coastal landmarks to quiet mountain hideaways, every Utopia home brings its own spirit to the trip.</p></section><section className="principles"><article><span>01</span><h3>Character,<br /><em>curated</em></h3><p>Homes selected for the details that make a destination feel singular.</p></article><article><span>02</span><h3>Care,<br /><em>consistent</em></h3><p>Professional standards behind every warm, welcoming moment.</p></article><article><span>03</span><h3>Belonging,<br /><em>rewarded</em></h3><p>A future membership created to make every return more meaningful.</p></article></section>{destinations.map((destination) => <section className="home-destination" key={destination.id}><div className="home-destination-image"><Image src={destination.heroImage.src} alt={destination.heroImage.alt} fill sizes="60vw" /></div><div><p className="eyebrow">Destination 01</p><h2>{destination.city}<br /><em>does it louder.</em></h2><p>{destination.longDescription}</p><Link className="text-link" href={`/destinations/${destination.slug}`}>Explore {destination.city} <span>→</span></Link></div></section>)}<section className="home-membership" id="membership"><div><p className="eyebrow eyebrow-light">Utopia membership</p><h2>Come back<br /><em>to more.</em></h2><p>Join the interest list for future rewards, benefits, and member-only opportunities.</p></div><LeadForm kind="membership" title="Stay close to what’s next." submitLabel="Join the list" /></section><CTASection /></>;
}
