"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { DesignAudience, DesignServiceId } from "@/types/content";
import type { AppliancePackage, DesignComplexity, DesignGrade, DesignLevel, DesignOption, PreliminaryQuote, QuoteInput, RenovationSeverity, RoomType, WalkthroughType } from "@/lib/design/types";
import { track } from "@/lib/analytics/events";

const services: Record<DesignServiceId, string> = {
  rental_readiness_audit: "Improve an Existing Rental", room_design_plan: "Transform a Room", whole_home_design_plan: "Design My Whole Home",
  renovation_design_plan: "Plan a Renovation or New Home", turnkey_furnishing: "Full-Service Furnishing",
};
const rentalServices: DesignServiceId[] = ["rental_readiness_audit", "turnkey_furnishing", "renovation_design_plan", "room_design_plan", "whole_home_design_plan"];
const personalServices: DesignServiceId[] = ["room_design_plan", "whole_home_design_plan", "renovation_design_plan", "turnkey_furnishing"];
const stepNames = ["Goal", "Property", "Facts", "Scope", "Vision", "Options", "Estimate", "Acknowledge"];
const options: Array<[DesignOption, string]> = [["visualization", "3D visualization"], ["additional_direction", "Additional design direction"], ["onsite_walkthrough", "On-site walkthrough"], ["rush", "Rush delivery"], ["outdoor_design", "Outdoor-space design"], ["additional_revision", "Additional revision round"]];
const roomLabels: Array<[RoomType, string]> = [["bedroom", "Bedrooms"], ["living_room", "Living rooms"], ["dining_room", "Dining rooms"], ["home_office", "Home offices"], ["kitchen", "Kitchens"], ["full_bathroom", "Full bathrooms"], ["half_bathroom", "Half bathrooms"], ["open_concept", "Open-concept areas"], ["specialty_room", "Game / specialty rooms"], ["outdoor_room", "Outdoor rooms"]];

interface QuoteResponse { ok: boolean; message?: string; quote?: PreliminaryQuote; reopenToken?: string; disclaimerVersion?: string; schedulerUrl?: string | null; }

export function QuoteStudio({ initialAudience, initialService }: { initialAudience: DesignAudience; initialService: DesignServiceId }) {
  const [step, setStep] = useState(0);
  const [audience, setAudience] = useState(initialAudience);
  const [serviceId, setServiceId] = useState(initialService);
  const [propertyMethod, setPropertyMethod] = useState<"address" | "listing" | "future">("address");
  const [address, setAddress] = useState(""); const [listingUrl, setListingUrl] = useState(""); const [propertyType, setPropertyType] = useState("Single-family home");
  const [livingArea, setLivingArea] = useState(1500); const [bedrooms, setBedrooms] = useState(3); const [bathrooms, setBathrooms] = useState(2); const [guestCapacity, setGuestCapacity] = useState(6);
  const [roomCount, setRoomCount] = useState(1); const [roomQuantities, setRoomQuantities] = useState<Partial<Record<RoomType, number>>>({ bedroom: 1 }); const [affectedArea, setAffectedArea] = useState(500); const [declaredBudget, setDeclaredBudget] = useState(0);
  const [kitchenIncluded, setKitchenIncluded] = useState(false); const [kitchens, setKitchens] = useState(0); const [fullBathrooms, setFullBathrooms] = useState(0); const [halfBathrooms, setHalfBathrooms] = useState(0);
  const [structuralChanges, setStructuralChanges] = useState(false); const [structuralConcepts, setStructuralConcepts] = useState(0); const [specialtySpaces, setSpecialtySpaces] = useState(0);
  const [outdoorIncluded, setOutdoorIncluded] = useState(false); const [outdoorArea, setOutdoorArea] = useState(0); const [outdoorZones, setOutdoorZones] = useState(0); const [structureCount, setStructureCount] = useState(1); const [complexity, setComplexity] = useState<DesignComplexity>("standard");
  const [designLevel, setDesignLevel] = useState<DesignLevel>("rental_focused"); const [renovationSeverity, setRenovationSeverity] = useState<RenovationSeverity>("moderate"); const [threeDRooms, setThreeDRooms] = useState(0); const [walkthrough, setWalkthrough] = useState<WalkthroughType>("none"); const [merchandise, setMerchandise] = useState(0); const [appliancePackage, setAppliancePackage] = useState<AppliancePackage>("none");
  const [files, setFiles] = useState<string[]>([]); const [inspiration, setInspiration] = useState(""); const [grade, setGrade] = useState<DesignGrade>("elegant"); const [selectedOptions, setSelectedOptions] = useState<DesignOption[]>([]);
  const [quote, setQuote] = useState<PreliminaryQuote | null>(null); const [reopenToken, setReopenToken] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [acknowledged, setAcknowledged] = useState(false); const [retentionAcknowledged, setRetentionAcknowledged] = useState(false); const [modelImprovementConsent, setModelImprovementConsent] = useState(false); const [complete, setComplete] = useState(false); const [schedulerUrl, setSchedulerUrl] = useState<string | null>(null);
  const availableServices = audience === "rental" ? rentalServices : personalServices;

  const input = useMemo<QuoteInput>(() => ({
    audience, serviceId, property: { address: propertyMethod === "address" ? address : "", listingUrl: propertyMethod === "listing" ? listingUrl : "", propertyType, livingArea, bedrooms, bathrooms, guestCapacity },
    scope: { roomCount, roomQuantities, affectedArea, declaredConstructionBudget: declaredBudget, kitchenIncluded, kitchens, fullBathrooms, halfBathrooms, structuralChanges, structuralChangeConcepts: structuralConcepts, specialtySpaces, outdoorIncluded, outdoorAffectedArea: outdoorArea, outdoorFurnishingZones: outdoorZones, structureCount, complexity, designLevel, renovationSeverity, threeDRooms, walkthrough, merchandiseToProcure: merchandise, appliancePackage, completeMedia: files.length > 0 }, grade, options: selectedOptions,
    informationCount: [address || listingUrl, propertyType, livingArea, bedrooms, bathrooms, guestCapacity, roomCount, affectedArea, inspiration, files.length, complexity, grade].filter(Boolean).length,
    retentionAcknowledged,
  }), [address, affectedArea, appliancePackage, audience, bathrooms, bedrooms, complexity, declaredBudget, designLevel, files.length, fullBathrooms, grade, guestCapacity, halfBathrooms, inspiration, kitchenIncluded, kitchens, listingUrl, livingArea, merchandise, outdoorArea, outdoorIncluded, outdoorZones, propertyMethod, propertyType, renovationSeverity, retentionAcknowledged, roomCount, roomQuantities, selectedOptions, serviceId, specialtySpaces, structuralChanges, structuralConcepts, structureCount, threeDRooms, walkthrough]);

  function updateAudience(next: DesignAudience) { setAudience(next); const allowed = next === "rental" ? rentalServices : personalServices; if (!allowed.includes(serviceId)) setServiceId(allowed[0]); }
  function toggleOption(option: DesignOption) { setSelectedOptions((current) => current.includes(option) ? current.filter((item) => item !== option) : [...current, option]); }
  function next() { setMessage(""); if (step === 1 && propertyMethod === "address" && address.trim().length < 5) { setMessage("Enter the property address, or choose another property option."); return; } if (step === 1 && propertyMethod === "listing" && !listingUrl.startsWith("http")) { setMessage("Enter the complete listing URL, including https://."); return; } track({ name: "quote_step_completed", properties: { audience, serviceId, quoteStep: step + 1 } }); setStep((current) => Math.min(7, current + 1)); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function previous() { setMessage(""); setStep((current) => Math.max(0, current - 1)); }

  async function generateQuote() {
    if (!retentionAcknowledged) { setMessage("Please acknowledge the project-data retention notice before generating the estimate."); return; }
    setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/design/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) });
      const result = await response.json() as QuoteResponse;
      if (!response.ok || !result.quote || !result.reopenToken) { setMessage(result.message || "We couldn’t generate the estimate."); return; }
      setQuote(result.quote); setReopenToken(result.reopenToken); setStep(6); window.scrollTo({ top: 0, behavior: "smooth" });
      track({ name: "quote_generated", properties: { audience, serviceId, quoteId: result.quote.id } });
    } catch { setMessage("We couldn’t reach the estimate service. Please try again."); } finally { setBusy(false); }
  }

  async function submitAcknowledgment(event: React.FormEvent) {
    event.preventDefault(); if (!quote || !acknowledged) return; setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/design/quotes/acknowledge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ quoteId: quote.id, reopenToken, name, email, phone, acknowledged, modelImprovementConsent, website: "" }) });
      const result = await response.json() as QuoteResponse;
      if (!response.ok) { setMessage(result.message || "We couldn’t save your acknowledgment."); return; }
      setComplete(true); setSchedulerUrl(result.schedulerUrl || null);
      track({ name: "quote_acknowledged", properties: { audience, serviceId, quoteId: quote.id } });
    } catch { setMessage("We couldn’t reach the acknowledgment service. Please try again."); } finally { setBusy(false); }
  }

  return <main className="quote-studio-page">
    <header className="quote-studio-header"><Link href={`/design?audience=${audience}`}>← Back to Utopia Design</Link><div><strong>Quote Studio</strong><span>Preliminary project estimate</span></div></header>
    <nav className="quote-progress" aria-label="Quote Studio progress"><ol>{stepNames.map((label, index) => <li key={label} aria-current={step === index ? "step" : undefined} data-complete={index < step}><span>{index + 1}</span><b>{label}</b></li>)}</ol></nav>
    <div className="quote-studio-shell">
      <p className="quote-step-label">Step {step + 1} of 8 · {stepNames[step]}</p>
      {step === 0 && <section aria-labelledby="quote-goal"><h1 id="quote-goal">What should this home become?</h1><p>Confirm the audience and outcome. Both can change without creating a separate calculator.</p><fieldset><legend>Space type</legend><div className="quote-choice-row"><label><input type="radio" checked={audience === "rental"} onChange={() => updateAudience("rental")} /> A vacation rental</label><label><input type="radio" checked={audience === "personal"} onChange={() => updateAudience("personal")} /> A home I live in</label></div></fieldset><fieldset><legend>Starting outcome</legend><div className="quote-card-choices">{availableServices.map((id) => <label key={id}><input type="radio" checked={serviceId === id} onChange={() => setServiceId(id)} /><span>{services[id]}</span></label>)}</div></fieldset></section>}
      {step === 1 && <section aria-labelledby="quote-property"><h1 id="quote-property">Tell us which home we’re working with.</h1><div className="quote-card-choices quote-methods">{(["address", "listing", "future"] as const).map((method) => <label key={method}><input type="radio" checked={propertyMethod === method} onChange={() => setPropertyMethod(method)} /><span>{method === "address" ? "Enter the property address" : method === "listing" ? "Enter a vacation-rental listing link" : "I don’t have a property yet"}</span></label>)}</div>{propertyMethod === "address" && <Field label="Property address"><input value={address} onChange={(event) => setAddress(event.target.value)} autoComplete="street-address" required /></Field>}{propertyMethod === "listing" && <Field label="Vacation-rental listing URL"><input type="url" value={listingUrl} onChange={(event) => setListingUrl(event.target.value)} required /></Field>}</section>}
      {step === 2 && <section aria-labelledby="quote-facts"><h1 id="quote-facts">Confirm the property facts.</h1><p>Every value is customer-confirmed. Licensed prefill can be added later without becoming authoritative.</p><div className="quote-field-grid"><Field label="Property type"><select value={propertyType} onChange={(event) => setPropertyType(event.target.value)}><option>Single-family home</option><option>Condominium</option><option>Townhome</option><option>Multi-family property</option><option>Property not selected</option></select></Field><NumberField label="Living area (sq. ft.)" value={livingArea} setValue={setLivingArea} /><NumberField label="Bedrooms" value={bedrooms} setValue={setBedrooms} /><NumberField label="Bathrooms" value={bathrooms} setValue={setBathrooms} step="0.5" /><NumberField label="Intended guest capacity" value={guestCapacity} setValue={setGuestCapacity} /></div></section>}
      {step === 3 && <section aria-labelledby="quote-scope"><h1 id="quote-scope">Confirm the project scope.</h1><div className="quote-field-grid"><Field label="Project complexity"><select value={complexity} onChange={(event) => setComplexity(event.target.value as DesignComplexity)}><option value="standard">Standard</option><option value="elevated">Elevated</option><option value="custom">Custom</option></select></Field>{serviceId === "room_design_plan" && roomLabels.map(([id, label]) => <NumberField key={id} label={label} value={roomQuantities[id] ?? 0} setValue={(value) => { const next = { ...roomQuantities, [id]: value }; setRoomQuantities(next); setRoomCount(Object.values(next).reduce((sum, quantity) => sum + (quantity ?? 0), 0)); }} />)}{serviceId === "whole_home_design_plan" && <NumberField label="Number of structures" value={structureCount} setValue={setStructureCount} />}{serviceId === "renovation_design_plan" && <><NumberField label="Affected area (sq. ft.)" value={affectedArea} setValue={setAffectedArea} /><NumberField label="Declared construction budget" value={declaredBudget} setValue={setDeclaredBudget} /><NumberField label="Kitchens" value={kitchens} setValue={(value) => { setKitchens(value); setKitchenIncluded(value > 0); }} /><NumberField label="Full bathrooms" value={fullBathrooms} setValue={setFullBathrooms} /><NumberField label="Half bathrooms" value={halfBathrooms} setValue={setHalfBathrooms} /><NumberField label="Structural-change concepts" value={structuralConcepts} setValue={(value) => { setStructuralConcepts(value); setStructuralChanges(value > 0); }} /><NumberField label="Outdoor affected area (sq. ft.)" value={outdoorArea} setValue={(value) => { setOutdoorArea(value); setOutdoorIncluded(value > 0); }} /></>}{["rental_readiness_audit", "renovation_design_plan", "turnkey_furnishing"].includes(serviceId) && <NumberField label="Specialty spaces" value={specialtySpaces} setValue={setSpecialtySpaces} />}{serviceId === "turnkey_furnishing" && <NumberField label="Outdoor furnishing zones" value={outdoorZones} setValue={(value) => { setOutdoorZones(value); setOutdoorIncluded(value > 0); }} />}</div></section>}
      {step === 4 && <section aria-labelledby="quote-vision"><h1 id="quote-vision">Show us the home and the vision.</h1><Field label="Inspiration or Pinterest link (optional)"><input type="url" value={inspiration} onChange={(event) => setInspiration(event.target.value)} /></Field><Field label="Select photos or plans for this estimate (optional)"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple onChange={(event) => setFiles(Array.from(event.target.files || []).slice(0, 20).map((file) => file.name))} /></Field><p className="quote-security-note">Selected files contribute to completeness but are not uploaded yet. Secure private storage will be enabled only after its provider and retention policy are approved.</p>{files.length > 0 && <p>{files.length} file{files.length === 1 ? "" : "s"} selected locally.</p>}</section>}
      {step === 5 && <section aria-labelledby="quote-options"><h1 id="quote-options">Select the design level and options.</h1>{serviceId === "whole_home_design_plan" && <Field label="Whole-home design level"><select value={designLevel} onChange={(event) => setDesignLevel(event.target.value as DesignLevel)}><option value="rental_focused">Rental-Focused · $4/sq. ft.</option><option value="elegant">Elegant · $5/sq. ft.</option><option value="utopian">Utopian · $6/sq. ft.</option></select></Field>}{serviceId === "renovation_design_plan" && <Field label="Renovation severity"><select value={renovationSeverity} onChange={(event) => setRenovationSeverity(event.target.value as RenovationSeverity)}><option value="cosmetic">Cosmetic</option><option value="moderate">Moderate</option><option value="major">Major</option></select></Field>}{serviceId === "turnkey_furnishing" && <><fieldset><legend>Furnishing grade</legend><div className="quote-card-choices">{(["rental", "elegant", "utopian"] as DesignGrade[]).map((item) => <label key={item}><input type="radio" checked={grade === item} onChange={() => setGrade(item)} /><span>{item === "rental" ? "Rental Grade · $35/sq. ft." : item === "elegant" ? "Elegant Grade · $45/sq. ft." : "Utopian Grade · $55/sq. ft."}</span></label>)}</div></fieldset><Field label="Appliance package"><select value={appliancePackage} onChange={(event) => setAppliancePackage(event.target.value as AppliancePackage)}><option value="none">None</option><option value="basic">Basic · $4,000</option><option value="enhanced">Enhanced · $8,000</option><option value="premium">Premium · $15,000</option></select></Field></>}{!["rental_readiness_audit", "turnkey_furnishing"].includes(serviceId) && <div className="quote-field-grid"><NumberField label="3D rooms" value={threeDRooms} setValue={setThreeDRooms} /><NumberField label="Merchandise to procure" value={merchandise} setValue={setMerchandise} /><Field label="On-site walkthrough"><select value={walkthrough} onChange={(event) => setWalkthrough(event.target.value as WalkthroughType)}><option value="none">None</option><option value="local">Local · $450</option><option value="regional">Regional · $750</option></select></Field></div>}<fieldset><legend>Optional additions</legend><div className="quote-check-list">{options.filter(([id]) => !["visualization", "onsite_walkthrough", "outdoor_design"].includes(id)).map(([id, label]) => <label key={id}><input type="checkbox" checked={selectedOptions.includes(id)} onChange={() => toggleOption(id)} /> {label}</label>)}</div></fieldset><label className="quote-ack-check"><input type="checkbox" checked={retentionAcknowledged} onChange={(event) => setRetentionAcknowledged(event.target.checked)} required /> I understand that the project information used to generate this estimate will be retained indefinitely for project history and business analysis. Model-improvement use requires a separate choice after the estimate.</label></section>}
      {step === 6 && quote && <section aria-labelledby="quote-reveal"><h1 id="quote-reveal">Your preliminary Utopia Design estimate</h1><div className="quote-total"><span>{quote.quoteNumber}</span><strong>{money(quote.total)}</strong><small>Exact preliminary total</small></div><dl className="quote-lines">{quote.lineItems.map((line) => <div key={line.code}><dt>{line.label}</dt><dd>{money(line.amount)}</dd></div>)}</dl><div className="quote-columns"><div><h2>Assumptions</h2><ul>{quote.assumptions.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h2>Exclusions</h2><ul>{quote.exclusions.map((item) => <li key={item}>{item}</li>)}</ul></div></div><p className="quote-completeness">Information completeness: <strong>{quote.completenessScore}%</strong> · Expires {new Date(quote.expiresAt).toLocaleDateString()}</p><p className="quote-disclaimer">This preliminary estimate is based on the information you provided and is intended for budgeting purposes only. It is not a binding quote. Final pricing will be confirmed after Utopia Design reviews the property, project scope, product availability, delivery requirements, and schedule.</p></section>}
      {step === 7 && quote && <section aria-labelledby="quote-acknowledge"><h1 id="quote-acknowledge">Save your estimate and unlock the consultation.</h1>{complete ? <div className="quote-success" role="status"><h2>Your project profile is saved.</h2><p>Your estimate has been acknowledged and the Utopia Design team has been notified.</p>{schedulerUrl ? <a className="button button-primary" href={schedulerUrl}>Schedule your complimentary consultation</a> : <><button className="button quote-calendar-disabled" type="button" disabled>Calendar scheduling · Coming soon</button><p className="quote-calendar-note">Online scheduling is planned but not active yet. The Utopia Design team will follow up directly.</p></>}</div> : <form onSubmit={submitAcknowledgment}><div className="quote-field-grid"><Field label="Name"><input value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" required minLength={2} /></Field><Field label="Email"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /></Field><Field label="Phone (optional)"><input type="tel" value={phone} onChange={(event) => setPhone(event.target.value)} autoComplete="tel" /></Field></div><label className="quote-ack-check"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} required /> I understand that this is a preliminary, nonbinding estimate and that final pricing will be confirmed after Utopia Design reviews the property and project scope.</label><label className="quote-ack-check"><input type="checkbox" checked={modelImprovementConsent} onChange={(event) => setModelImprovementConsent(event.target.checked)} /> Optional: Utopia may use de-identified information from this project to improve future tools and models. This choice is not required to receive an estimate or consultation.</label><button className="button button-primary" type="submit" disabled={busy || !acknowledged}>{busy ? "Saving…" : "Save My Estimate"}</button></form>}</section>}
      <p className="quote-message" aria-live="polite">{message}</p>
      {!complete && <div className="quote-actions">{step > 0 && <button type="button" className="button" onClick={previous}>Back</button>}{step < 5 && <button type="button" className="button button-primary" onClick={next}>Continue</button>}{step === 5 && <button type="button" className="button button-primary" onClick={generateQuote} disabled={busy || !retentionAcknowledged}>{busy ? "Calculating…" : "Generate My Estimate"}</button>}{step === 6 && <button type="button" className="button button-primary" onClick={next}>Review and Acknowledge</button>}</div>}
    </div>
  </main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="quote-field"><span>{label}</span>{children}</label>; }
function NumberField({ label, value, setValue, step = "1" }: { label: string; value: number; setValue: (value: number) => void; step?: string }) { return <Field label={label}><input type="number" min="0" step={step} value={value} onChange={(event) => setValue(Number(event.target.value))} /></Field>; }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
