"use client";
import { useState } from "react";
import { track } from "@/lib/analytics/events";
import type { FormKind } from "@/lib/forms/schemas";

type Field = { name: string; label: string; type?: "text" | "email" | "tel" | "url" | "number" | "textarea" | "select"; required?: boolean; options?: { label: string; value: string }[]; placeholder?: string };
const fields: Record<FormKind, Field[]> = {
  "owner-lead": [{ name: "name", label: "Your name", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "listingUrl", label: "Airbnb or Vrbo listing URL", type: "url", placeholder: "https://" }, { name: "propertyAddress", label: "No listing yet? Property address" }, { name: "notes", label: "What would you like ownership to feel like?", type: "textarea" }],
  membership: [{ name: "name", label: "Your name", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "zip", label: "ZIP code" }, { name: "travelInterests", label: "What kind of trips bring you together?", type: "textarea" }],
  contact: [{ name: "name", label: "Your name", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "inquiryType", label: "How can we help?", type: "select", required: true, options: [{ label: "Select one", value: "" }, { label: "Guest question", value: "guest" }, { label: "List my home", value: "owner" }, { label: "Property enhancement", value: "design" }, { label: "General", value: "general" }] }, { name: "message", label: "Your message", type: "textarea", required: true }],
  "design-inquiry": [{ name: "name", label: "Your name", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "phone", label: "Phone", type: "tel" }, { name: "propertyAddress", label: "Property address" }, { name: "projectType", label: "What are you considering?", type: "select", required: true, options: [{ label: "Select one", value: "" }, { label: "Assessment", value: "assessment" }, { label: "Interior design", value: "interior-design" }, { label: "Furnishing", value: "furnishing" }, { label: "Amenity strategy", value: "amenity-strategy" }, { label: "Photography readiness", value: "photography" }] }, { name: "message", label: "Tell us about the opportunity", type: "textarea", required: true }],
};
const eventNames = { "owner-lead": "owner_lead_submit", membership: "membership_signup", contact: "contact_submit", "design-inquiry": "design_service_interest" } as const;
export function LeadForm({ kind, title, submitLabel }: { kind: FormKind; title: string; submitLabel: string }) {
  const [status, setStatus] = useState<{ state: "idle" | "sending" | "success" | "error"; message?: string }>({ state: "idle" });
  async function onSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus({ state: "sending" }); const form = event.currentTarget; const formData = new FormData(form); const query = new URLSearchParams(location.search); const attribution = { source: document.referrer || "direct", referrer: document.referrer, utmSource: query.get("utm_source") ?? "", utmMedium: query.get("utm_medium") ?? "", utmCampaign: query.get("utm_campaign") ?? "", utmContent: query.get("utm_content") ?? "", utmTerm: query.get("utm_term") ?? "" }; const data: Record<string, unknown> = Object.fromEntries(formData.entries()); data.consent = Boolean(formData.get("consent")); const response = await fetch(`/api/forms/${kind}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, ...attribution }) }); const result = await response.json(); if (response.ok) { setStatus({ state: "success", message: result.message }); track({ name: eventNames[kind], properties: { source: attribution.source, utmCampaign: attribution.utmCampaign } }); form.reset(); } else setStatus({ state: "error", message: result.message ?? "Something went wrong. Please try again." }); }
  if (status.state === "success") return <div className="form-success" role="status"><span>✓</span><h3>Received.</h3><p>{status.message}</p></div>;
  return <form className="lead-form" onSubmit={onSubmit} noValidate><div className="form-heading"><p className="eyebrow">Start a conversation</p><h2>{title}</h2></div><div className="form-grid">{fields[kind].map((field) => <label key={field.name} className={field.type === "textarea" ? "field-wide" : ""}><span>{field.label}{field.required && " *"}</span>{field.type === "textarea" ? <textarea name={field.name} required={field.required} rows={5} /> : field.type === "select" ? <select name={field.name} required={field.required}>{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input name={field.name} type={field.type ?? "text"} required={field.required} placeholder={field.placeholder} />}</label>)}<label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><label className="consent field-wide"><input name="consent" type="checkbox" required /><span>I agree that Utopia Homes may contact me about this request. *</span></label></div>{status.state === "error" && <p className="form-error" role="alert">{status.message}</p>}<button className="button button-primary form-submit" disabled={status.state === "sending"} type="submit">{status.state === "sending" ? "Sending…" : submitLabel} <span aria-hidden="true">→</span></button></form>;
}
